apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-test
  template:
    metadata:
      labels:
        app: my-test
    spec:
      containers:
      - name: my-test
        image: registry.cn-shenzhen.aliyuncs.com/dyf_test/my_test:v1
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name:  my-test-registrykey

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-claster-ip-service
spec:
  type: ClusterIP
  selector:
    app: my-test
  ports:
  - port: 80
    targetPort: 80